[build]
  # Directory to deploy. Your index.html is in here.
  publish = "public/"
  
  # Directory where the Netlify Functions are located.
  functions = "netlify/functions/"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200